<a href="https://colab.research.google.com/github/JohnPatrickChipongian/Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Matrix and its Operations

In [ ]:
import numpy as np
a = np.array([
    [1,2,3]           #is a 1,3 matrix
])
print(a)

[[1 2 3]]


In [ ]:
b = np.array([
              [1,2,3],
              [4,5,6]
])
print(b)
b[0][0]=7
print(b)

[[1 2 3]
 [4 5 6]]
[[7 2 3]
 [4 5 6]]


In [ ]:
d = np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [ ]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
f = np.diagonal([
                   [4,7,4],
                   [4,8,5],
                   [1,9,0]
])
t = np.diagonal(e)
print(f)
print(t)

[4 8 0]
[1. 1. 1. 1. 1.]


In [ ]:
g = np.empty((0,10))
print(g)
h = np.zeros((5,5))
print(h)

[]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(e+h)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
print(h-e)

[[-1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.]]
