<a href="https://colab.research.google.com/github/JohnPatrickChipongian/Numerical-Methods/blob/main/Python_Excercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

C = np.array([[-5, 0], [4, 1]])
H = np.array([[6, -3], [2, 3]])

I = C + H      #  Sum
P = C - H      #  Diff 1
S = H - C      #  Diff 2

print(C)
print(H)

print("-----------------------------")
print(I)
print("-----------------------------")
print(P)
print("-----------------------------")
print(S)
print("-----------------------------")

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
-----------------------------
[[ 1 -3]
 [ 6  4]]
-----------------------------
[[-11   3]
 [  2  -2]]
-----------------------------
[[11 -3]
 [-2  2]]
-----------------------------
